export const ROUTES = {
    HOME: '/home',
    LOGIN: '/login',
    REGISTER: '/register',
    COURSE_LIST: '/course',
    CATEGORIES: '/categories',
    MY_COURSES: '/my-courses',
    PROGRAMS: '/programs',
    MY_PROGRAMS: '/my-programs',
    PROFILE: '/profile',
    CONTACT: '/contact',
    
    // Admin Routes
    ADMIN_DASHBOARD: '/admin',
    ADMIN_COURSES: '/admin/courses',
    ADMIN_USERS: '/admin/users',
    ADMIN_REQUESTS: '/admin/requests',
    ADMIN_PROGRAMS: '/admin/programs',
    ADMIN_CATEGORIES: '/admin/categories',
    ADMIN_PROGRESS: '/admin/progress',
    ADMIN_BANNERS: '/admin/banners',
    ADMIN_DEPARTMENTS: '/admin/departments',
    ADMIN_POSITIONS: '/admin/positions',
    ADMIN_ROLES: '/admin/roles',
    ADMIN_ONBOARDING_REPORT: '/admin/onboarding-report',
    MANAGER_EMPLOYEES: '/admin/manager/employees',
};
